const u14GirlsRoster = [
  { name: "Jordan Davis", role: "Coach", status: "In progress", completed: "—", overdue: false },
  { name: "Elena Ruiz", role: "Coach", status: "Complete", completed: "Sep 4", overdue: false },
  { name: "Marcus Lee", role: "Coach", status: "Complete", completed: "Sep 7", overdue: false },
  { name: "Avery Bennett", role: "Parent", status: "Complete", completed: "Sep 2", overdue: false },
  { name: "Sofia Martinez", role: "Parent", status: "Complete", completed: "Sep 5", overdue: false },
  { name: "David Chen", role: "Parent", status: "In progress", completed: "—", overdue: false },
  { name: "Rachel Thompson", role: "Parent", status: "Not started", completed: "—", overdue: true },
  { name: "Nina Patel", role: "Parent", status: "Complete", completed: "Sep 8", overdue: false },
  { name: "Chris Morgan", role: "Parent", status: "In progress", completed: "—", overdue: false },
  { name: "Tanya Brooks", role: "Parent", status: "Complete", completed: "Sep 10", overdue: false },
  { name: "Samuel Wright", role: "Parent", status: "Not started", completed: "—", overdue: true },
  { name: "Kelly Foster", role: "Parent", status: "Complete", completed: "Sep 12", overdue: false },
] as const;

export const demoData = {
  mentor: {
    firstName: "Jordan",
    lastName: "Davis",
    email: "jordan@example.com",
    initials: "JD",
  },
  athlete: {
    firstName: "Maya",
  },
  overview: {
    weeklyStreak: "4 weeks",
    lessonsCompleted: "8 lessons",
    pulseScore: 76,
    pulseUpdated: "7 days ago",
    totalXp: 425,
  },
  wellbeingHistory: [
    ["Apr 7", 72],
    ["Apr 14", 78],
    ["Apr 21", 65],
    ["Apr 28", 82],
    ["May 5", 76],
    ["This week", 80],
  ] as const,
  recentContext: [
    ["Today", "Weekly check-in due", "bg-[#f4c66a]"],
    ["3 days ago", "High training load", "bg-[#efe7ff]"],
    ["1 week ago", "Away competition", "bg-[#d9ff54]"],
  ] as const,
  learning: {
    unitNumber: 1,
    unitCount: 4,
    stepsComplete: 2,
    stepsTotal: 7,
    progressPercent: 29,
    weeklyGoalComplete: 2,
    weeklyGoalTotal: 3,
    weeklyGoalDays: [true, true, false],
    exampleGameXp: 100,
  },
  courses: {
    parent: {
      title: "The Car Ride Home: a course for sports parents",
      status: "In progress",
      progress: 72,
    },
    coach: {
      title: "Coaching the Whole Athlete: a course for coaches",
      status: "In progress",
      progress: 58,
    },
  },
  team: {
    name: "U14 Girls, Fall season",
    completion: {
      parentsComplete: 5,
      parentsTotal: 9,
      coachesComplete: 2,
      coachesTotal: 3,
      percent: 58,
    },
    roster: u14GirlsRoster,
    pulse: [
      ["Mood", 78],
      ["Enjoyment", 82],
      ["Pressure", 64],
      ["Recovery", 71],
      ["Connection", 85],
    ],
  },
  certificates: [
    {
      id: "TEAM-DEMO-2026",
      name: "Elena Ruiz",
      course: "Coaching the Whole Athlete: a course for coaches",
      completed: "September 4, 2026",
    },
  ],
  admin: {
    organization: {
      name: "Ridgeview Athletic Club",
      type: "Club",
      season: "Fall season",
    },
    figures: {
      completionRate: 56,
      enrolled: 36,
      complete: 20,
      overdue: 8,
    },
    teams: [
      {
        id: "u14-girls",
        name: "U14 Girls",
        sport: "Soccer",
        season: "Fall season",
        dueDate: "September 15, 2026",
        coaches: 3,
        parents: 9,
        completion: 58,
        complete: 7,
        joinLink: "/join/U14GIRLS",
        roster: u14GirlsRoster,
      },
      {
        id: "u16-boys",
        name: "U16 Boys",
        sport: "Basketball",
        season: "Fall season",
        dueDate: "September 18, 2026",
        coaches: 2,
        parents: 6,
        completion: 38,
        complete: 3,
        joinLink: "https://teaminstitute.org/join/u16-boys",
        roster: [
          { name: "Andre Walker", role: "Coach", status: "Complete", completed: "Sep 6", overdue: false },
          { name: "Luis Romero", role: "Coach", status: "In progress", completed: "—", overdue: true },
          { name: "Monica Hall", role: "Parent", status: "Complete", completed: "Sep 8", overdue: false },
          { name: "Peter Kim", role: "Parent", status: "Complete", completed: "Sep 9", overdue: false },
          { name: "Dana Scott", role: "Parent", status: "In progress", completed: "—", overdue: false },
          { name: "Priya Shah", role: "Parent", status: "Not started", completed: "—", overdue: true },
          { name: "Robert Miles", role: "Parent", status: "Not started", completed: "—", overdue: true },
          { name: "Keisha Young", role: "Parent", status: "In progress", completed: "—", overdue: false },
        ],
      },
      {
        id: "u12-coed",
        name: "U12 Coed",
        sport: "Soccer",
        season: "Fall season",
        dueDate: "September 20, 2026",
        coaches: 2,
        parents: 6,
        completion: 75,
        complete: 6,
        joinLink: "https://teaminstitute.org/join/u12-coed",
        roster: [
          { name: "Erin Walsh", role: "Coach", status: "Complete", completed: "Sep 3", overdue: false },
          { name: "Malik Johnson", role: "Coach", status: "Complete", completed: "Sep 4", overdue: false },
          { name: "Grace Liu", role: "Parent", status: "Complete", completed: "Sep 5", overdue: false },
          { name: "Omar Hassan", role: "Parent", status: "Complete", completed: "Sep 6", overdue: false },
          { name: "Bethany Cole", role: "Parent", status: "Complete", completed: "Sep 7", overdue: false },
          { name: "Victor Reyes", role: "Parent", status: "Complete", completed: "Sep 8", overdue: false },
          { name: "Allison Price", role: "Parent", status: "In progress", completed: "—", overdue: false },
          { name: "Henry Adams", role: "Parent", status: "Not started", completed: "—", overdue: true },
        ],
      },
      {
        id: "varsity-track",
        name: "Varsity Track",
        sport: "Track and field",
        season: "Fall season",
        dueDate: "September 22, 2026",
        coaches: 2,
        parents: 6,
        completion: 50,
        complete: 4,
        joinLink: "https://teaminstitute.org/join/varsity-track",
        roster: [
          { name: "Nicole Grant", role: "Coach", status: "Complete", completed: "Sep 5", overdue: false },
          { name: "Terrence Bell", role: "Coach", status: "Complete", completed: "Sep 7", overdue: false },
          { name: "Megan Ross", role: "Parent", status: "Complete", completed: "Sep 8", overdue: false },
          { name: "Ian Cooper", role: "Parent", status: "Complete", completed: "Sep 10", overdue: false },
          { name: "Felicia Ward", role: "Parent", status: "In progress", completed: "—", overdue: false },
          { name: "George Evans", role: "Parent", status: "Not started", completed: "—", overdue: true },
          { name: "Lena Ortiz", role: "Parent", status: "In progress", completed: "—", overdue: false },
          { name: "Caleb Turner", role: "Parent", status: "Not started", completed: "—", overdue: true },
        ],
      },
    ],
    administrators: [
      { name: "Morgan Reed", role: "Program administrator" },
      { name: "Elena Ruiz", role: "Coach administrator" },
    ],
    billingContact: {
      name: "Morgan Reed",
      email: "morgan@ridgeview.example",
    },
    plan: "Education, 4 teams, Fall season",
    wellbeingContact: "Not set",
    reportGenerated: "September 24, 2026",
    invoices: [
      { date: "August 15, 2026", description: "Fall season · 4 teams", amount: "$796", status: "Paid" },
      { date: "November 15, 2026", description: "Winter season deposit", amount: "$398", status: "Due" },
    ],
  },
  account: {
    teams: [
      { name: "U14 Girls", role: "Coach" },
      { name: "U12 Coed", role: "Parent" },
    ],
    emailPreferences: {
      courseReminders: true,
      teamAnnouncements: true,
    },
  },
  join: {
    code: "U14GIRLS",
    teamName: "U14 Girls",
    organization: "Ridgeview Athletic Club",
    sport: "Soccer",
    season: "Fall season",
    dueDate: "September 15, 2026",
  },
  staff: {
    figures: {
      organizations: 4,
      activeTeams: 18,
      peopleEnrolled: 236,
      completionRate: 70,
    },
    organizations: [
      {
        name: "Ridgeview Athletic Club",
        type: "Club",
        plan: "Education",
        teams: 4,
        people: 36,
        completion: 56,
        seasonEnd: "November 16, 2026",
        contactRequests: 7,
      },
      {
        name: "Northfield High School",
        type: "High school",
        plan: "Education",
        teams: 6,
        people: 84,
        completion: 72,
        seasonEnd: "November 22, 2026",
        contactRequests: 11,
      },
      {
        name: "Summit United",
        type: "Club",
        plan: "Education",
        teams: 5,
        people: 71,
        completion: 81,
        seasonEnd: "December 6, 2026",
        contactRequests: 9,
      },
      {
        name: "Lakeview High School",
        type: "High school",
        plan: "Education",
        teams: 3,
        people: 45,
        completion: 58,
        seasonEnd: "November 20, 2026",
        contactRequests: 4,
      },
    ],
    demoRequests: [
      { date: "Sep 18, 2026", name: "Alicia Monroe", organization: "Eastside Soccer Club", type: "Club", athletes: 180, status: "New" },
      { date: "Sep 17, 2026", name: "Devon Price", organization: "Central High School", type: "High school", athletes: 320, status: "Contacted" },
      { date: "Sep 15, 2026", name: "Mei Tan", organization: "River City Volleyball", type: "Club", athletes: 96, status: "Scheduled" },
      { date: "Sep 12, 2026", name: "Brian Keller", organization: "Westbrook High School", type: "High school", athletes: 240, status: "Contacted" },
    ],
    emails: {
      invitation: {
        team: "U14 Girls",
        inviter: "Elena Ruiz",
        dueDate: "September 15",
      },
      reminder: {
        team: "U14 Girls",
        dueDate: "September 15",
        stopsComplete: 6,
        minutesRemaining: 32,
      },
      completion: {
        course: "Coaching the Whole Athlete",
        certificateId: "TEAM-DEMO-2026",
      },
      summary: {
        organization: "Ridgeview Athletic Club",
        completion: 56,
        overdue: 8,
        teams: [
          { name: "U14 Girls", completion: 58 },
          { name: "U16 Boys", completion: 38 },
          { name: "U12 Coed", completion: 75 },
          { name: "Varsity Track", completion: 50 },
        ],
      },
    },
  },
  athletePreview: {
    firstName: "Maya",
    age: 14,
    team: "U14 Girls",
    todaySkill: {
      name: "Reset after a mistake",
      duration: "3 min",
    },
    streak: 4,
    skillsCompleted: 9,
    themes: [
      { name: "Reset after a mistake", sessions: 3, progress: 67 },
      { name: "Pre-competition routine", sessions: 4, progress: 50 },
      { name: "Self-talk", sessions: 3, progress: 33 },
      { name: "Breathing", sessions: 2, progress: 100 },
      { name: "Sleep and recovery", sessions: 3, progress: 25 },
      { name: "Handling pressure", sessions: 4, progress: 0 },
    ],
    streakCalendar: [
      { day: "M", complete: true },
      { day: "T", complete: true },
      { day: "W", complete: true },
      { day: "T", complete: true },
      { day: "F", complete: false },
      { day: "S", complete: false },
      { day: "S", complete: false },
    ],
    wellbeingContact: {
      name: "Morgan Reed",
      role: "Student support coordinator",
    },
  },
  professional: {
    demoState: "Matched",
    requestsThisSeason: 7,
    responseTime: "2 school days",
    sample: {
      name: "Dr. Avery Morgan",
      title: "Licensed Psychologist",
      label: "Sample",
      credentials: "Psy.D.",
      licenseState: "Pennsylvania",
      licenseNumber: "PS019245",
      email: "avery.morgan@example.com",
      phone: "(555) 014-0192",
      availability: "Monday, Wednesday, Friday",
    },
    ownSample: {
      name: "Dr. Leah Park",
      credentials: "Ph.D.",
      license: "New Jersey SI 06124",
      email: "leah.park@example.com",
      phone: "(555) 014-0188",
      availability: "Tuesday and Thursday",
    },
    wellbeingContact: {
      name: "Morgan Reed",
      email: "morgan@ridgeview.example",
    },
    contactRequests: [
      {
        id: "request-1",
        date: "Sep 22, 2026",
        role: "Athlete",
        method: "Phone",
        preferredTime: "After 3:00 PM",
        status: "New",
        name: "Maya P.",
        email: "maya.parent@example.com",
        phone: "(555) 014-0118",
        message: "Please contact me after school.",
      },
      {
        id: "request-2",
        date: "Sep 20, 2026",
        role: "Parent",
        method: "Email",
        preferredTime: "Evening",
        status: "Contacted",
        name: "David Chen",
        email: "david.chen@example.com",
        phone: "(555) 014-0134",
        message: "Email is the easiest way to reach me.",
      },
      {
        id: "request-3",
        date: "Sep 18, 2026",
        role: "Coach",
        method: "Phone",
        preferredTime: "Morning",
        status: "Closed",
        name: "Elena Ruiz",
        email: "elena.ruiz@example.com",
        phone: "(555) 014-0167",
        message: "",
      },
    ],
  },
} as const;
